src/java/com/listamascotas/Controlador/ListaMascotasController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.listamascotas.Controlador;

import com.listamascota.Modelo.Nodo;
import com.listamascota.Modelo.Perro;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;

/**
 *
 * @author marthalucia
 */
@Named(value = "listaMascotasController")
@SessionScoped
public class ListaMascotasController implements Serializable {
        
    private listaDME lista = new listaDME();


    private Nodo temp;
    private Perro PerroAdicionar;
    private boolean verNuevo = false;
    private boolean verBuscar = false;
    private String listado;
    private Perro perroEncontrado;
    private int posicionBuscar = 0;


    public boolean isVerBuscar() {
        return verBuscar;
    }

    public Perro getPerroEncontrado() {
        return perroEncontrado;
    }

    public int getPosicionBuscar() {
        return posicionBuscar;
    }

    public void setPosicionBuscar(int posicionBuscar) {
        this.posicionBuscar = posicionBuscar;
    }

    public void setPerroEncontrado(Perro perroEncontrado) {
        this.perroEncontrado = perroEncontrado;
    }

    public void setVerBuscar(boolean verBuscar) {
        this.verBuscar = verBuscar;
    }

    public String getListado() {
        return listado;
    }

    public void setListado(String listado) {
        this.listado = listado;
    }

    public listaDME getLista() {
        return lista;
    }

    public void setLista(listaDME lista) {
        this.lista = lista;
    }

    public Nodo getTemp() {
        return temp;
    }

    public void setTemp(Nodo temp) {
        this.temp = temp;
    }

    public Perro getPerroAdicionar() {
        return PerroAdicionar;
    }

    public void setPerroAdicionar(Perro PerroAdicionar) {
        this.PerroAdicionar = PerroAdicionar;
    }

    public boolean isVerNuevo() {
        return verNuevo;
    }

    public void setVerNuevo(boolean verNuevo) {
        this.verNuevo = verNuevo;
    }

    
    public void adicionarPerroAlInicio(String nombre, byte edad, byte NumeroPulgas, String raza) {
        Perro nuevo = new Perro(nombre, edad, NumeroPulgas, raza);

        lista.adicionarInicio(nuevo);

    }

    public void adicionarPerroFinal(String nombre, byte edad, byte NumeroPulgas, String raza) {
        Perro nuevo = new Perro(nombre, edad, NumeroPulgas, raza);

        lista.adicionarFinal(nuevo);

    }

    public ListaMascotasController()
    {


        mostrarListado();
        temp = lista.getCabeza();
    }

    public void habilitarBuscar() {
        verBuscar = true;
    }

    public void mostrarListado() {
        listado = lista.listarNodo();
    }

    public void verCrearPerro() {
        verNuevo = true;
        PerroAdicionar = new Perro();
    }

    public void irAlsiguiente() {
        if (temp.getSiguiente() != null) {
            temp = temp.getSiguiente();
        }
    }

    public void irAnterior() {
        if (temp.getAnterior()!= null) {
            temp = temp.getAnterior();
        }
    }

    public void irAlPrimero() {
        temp = lista.getCabeza();
    }

    public void irAlUltimo() {
        Nodo ultimo = lista.obtenerUltimoNodo();
        if (ultimo != null) {
            temp = ultimo;
        }
    }
    
   


    public void buscarPorPosicion() {
        perroEncontrado = lista.obtenerNodoxPosicion(posicionBuscar)
                .getDato();
    }

    public void adicionarAlInicio() {
        lista.adicionarInicio(PerroAdicionar);
        irAlPrimero();
        verNuevo = false;
    }

    public void adicionarAlFinal() {
        lista.adicionarFinal(PerroAdicionar);
        irAlPrimero();
        verNuevo = false;
    }

    public void eliminarPrimero() {
        lista.eliminarInicio();
    }

    public void eliminarFinal() {
        lista.eliminarFinal();
    }

    public void eliminarPosicion() {
        lista.eliminarPosicion(posicionBuscar);
    }

    public void cambiarLista() {
        lista.cambiarLista();
    }
    
    public void obtenervocal() {
        lista.obtenervocal();
        irAlPrimero();
        
    }
    
}

    

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
        <br />
        <h:link outcome="welcomePrimefaces" value="Primefaces welcome page" />
    </h:body>
</html>

web/lista/gestionlista.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title> Lista de mascotas doblemente enlazada </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    </h:head>
    <h:body>

        <h:form>

            <p:panel header="Lista  de perros">

                <h:panelGrid columns="2" id="hpgDatos">

                    <p:outputLabel value="Nombre:" />
                    <p:outputLabel  value="#{listaMascotasController.temp.dato.nombre}"/>

                    <p:outputLabel value="Raza:" />
                    <p:outputLabel value="#{listaMascotasController.temp.dato.raza}" />

                    <p:outputLabel value="Edad:" />
                    <p:outputLabel value="#{listaMascotasController.temp.dato.edad}" />

                    <p:outputLabel value="Cantidad de Pulgas:" />
                    <p:outputLabel value="#{listaMascotasController.temp.dato.numeroPulgas}" />


                </h:panelGrid>

                <h:panelGrid columns="5">
                    <p:commandButton value="Primero" update="hpgDatos" action="#{listaMascotasController.irAlPrimero()}" />  
                    <p:commandButton value="Anterior" update="hpgDatos" action="#{listaMascotasController.irAnterior()}" />
                    <p:commandButton value="Siguiente" update="hpgDatos" action="#{listaMascotasController.irAlsiguiente()}" />
                    <p:commandButton value="Último" update="hpgDatos" action="#{listaMascotasController.irAlUltimo()}" />
                </h:panelGrid>


                <center>



                    <h:panelGroup id="hpgCrear">

                        <p:commandButton value="Nuevo"  update="hpgCrear" 
                                         rendered="#{!listaMascotasController.verNuevo}"
                                         action="#{listaMascotasController.verCrearPerro()}"  />


                        <p:commandButton value="Buscar por Posición" action="#{listaMascotasController.habilitarBuscar()}"
                                         update="hpgBuscarPosicion" />

                        <p:commandButton value="Eliminar primero" action="#{listaMascotasController.eliminarPrimero()}" update="hpgDatos"/> 


                        <p:commandButton value="Eliminar X posicion" action="#{listaMascotasController.habilitarBuscar()}"
                                         update="hpgEliminarPosicion"/>


                        <p:commandButton value="Invertir lista" update="hpgDatos" action="#{listaMascotasController.invertirLista()}"/>
                        <p:commandButton value="Vocales" update="hpgDatos" action="#{listaMascotasController.obtenervocal()}"/>

                      


                        <p:panel header="Crear   nuevo perro" rendered="#{listaMascotasController.verNuevo}" >

                            <h:outputLabel  value="Nombre"/> 

                            <p:inputText value="#{listaMascotasController.perroAdicionar.nombre}"/>

                            <h:outputLabel  value="Raza"/> 

                            <p:inputText value="#{listaMascotasController.perroAdicionar.raza}"/>
                            <h:outputLabel  value="Edad"/> 

                            <p:inputText value="#{listaMascotasController.perroAdicionar.edad}"/>

                            <h:outputLabel  value="Cantidad de pulgas"/> 

                            <p:inputText value="#{listaMascotasController.perroAdicionar.numeroPulgas}"/>


                            <p:commandButton value="Adicionar al inicio" update="@all"
                                             action="#{listaMascotasController.adicionarAlInicio()}"/>
                            <p:commandButton value="Adicionar al Final" update="@all"
                                             action="#{listaMascotasController.adicionarAlFinal()}"/>

                        </p:panel>

                    </h:panelGroup>




                    <h:panelGroup id="hpgBuscarPosicion">
                        <p:panel header="Buscar x Posición" rendered="#{listaMascotasController.verBuscar}">

                            <p:inputText value="#{listaMascotasController.posicionBuscar}"/> 

                            <p:commandButton value="Obtener x Posición" action="#{listaMascotasController.buscarPorPosicion()}"
                                             update="hpgBuscarPosicion"/>
                            <p:panelGrid columns="4" >

                                <p:outputLabel 
                                    value="#{listaMascotasController.perroEncontrado.nombre}" />
                                <p:outputLabel 
                                    value="#{listaMascotasController.perroEncontrado.edad}"/>

                                <p:outputLabel 
                                    value="#{listaperrosControllerDoble.perroEncontrado.raza}"/>

                                <p:outputLabel 
                                    value="#{listaMascotasController.perroEncontrado.numeroPulgas}" />




                            </p:panelGrid>
                        </p:panel>
                    </h:panelGroup>

                    <h:panelGroup id="hpgEliminarPosicion">
                        <p:panel header="Eliminar x Posición" rendered="#{listaMascotasController.verBuscar}">
                            <p:inputText value="#{listaMascotasController.posicionBuscar}"/> 
                            <p:commandButton value="posición que desea eliminar" action="#{listaMascotasController.eliminarPosicion()}"
                                             update="@all"/>

                        </p:panel>
                    </h:panelGroup>
                </center>
            </p:panel>
        </h:form>
    </h:body>
</html>

web/welcomePrimefaces.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <a href="welcomePrimefaces.xhtml"></a>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>PrimeFaces</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="true" closable="true" collapsible="true">
                    Header
                </p:layoutUnit>

                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    Footer
                </p:layoutUnit>

                <p:layoutUnit position="west" size="175" header="Left" collapsible="true">
                    <p:menu>
                        <p:submenu label="Resources">
                            <p:menuitem value="Demo" url="http://www.primefaces.org/showcase-labs/ui/home.jsf" />
                            <p:menuitem value="Documentation" url="http://www.primefaces.org/documentation.html" />
                            <p:menuitem value="Forum" url="http://forum.primefaces.org/" />
                            <p:menuitem value="Themes" url="http://www.primefaces.org/themes.html" />

                        </p:submenu>

                    </p:menu>
                </p:layoutUnit>

                <p:layoutUnit position="center">
                    Welcome to PrimeFaces
                </p:layoutUnit>

            </p:layout>

        </h:body>

    </f:view>
</html>